// This file is auto-generated by scripts/sync-cards.js
// Do not edit manually. run 'npm run sync-cards' to update.

import type { CardData } from '../types';

export const GAME_CARDS: CardData[] = [
    {
        "cardFamily": "Utility",
        "id": "void_blast",
        "name": "Void Blast",
        "type": "Action",
        "subType": "Normal",
        "effectText": "Deal 50 damage to your opponent."
    },
    {
        "cardFamily": "Utility",
        "id": "reinforcement",
        "name": "Reinforcement",
        "type": "Condition",
        "subType": "Normal",
        "effectText": "Target 1 pawn on the field, it gains +20 ATK."
    },
    {
        "cardFamily": "Pawn",
        "id": "force_fire_sparker",
        "name": "Force Fire Sparker",
        "level": 2,
        "attribute": "Fire",
        "pawnType": "Demon",
        "effectText": "ON NORMAL SUMMON: Deal 10 damage for each set Action/Condition on opponent's field.",
        "attack": 30,
        "defense": 150
    },
    {
        "cardFamily": "Pawn",
        "id": "high_king_of_the_west",
        "name": "High King of the West",
        "level": 5,
        "attribute": "Earth",
        "pawnType": "Warrior",
        "effectText": "ON SUMMON: Target 1 face-up monster on the field; it loses 20 ATK.",
        "attack": 170,
        "defense": 50
    },
    {
        "cardFamily": "Pawn",
        "id": "solstice_sentinel",
        "name": "Solstice Sentinel",
        "level": 4,
        "attribute": "Light",
        "pawnType": "Mechanical",
        "effectText": "When this card is summoned gain 100 lifepoints.",
        "attack": 120,
        "defense": 100
    }
];
